spring:
  application:
    name: Config
  cloud:
    config:
      server:
        git:
          uri: xxx
          clone-on-start: true
          username: xxx
          password: xxx
          basedir: /app/share/configurations
          force-pull: true
server.port: 8888